name: CI pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Welcome Message
        run: echo "GitHub Actions CI pipeline Executed Successfully!"

      - name: Display Current Directory
        run: pwd

      - name: List project Files
        run: ls -la

      - name: Display completion Message
        run: echo "Pipeline Completed Successfully."